name: Build, Test, and Deploy for Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      TEST_USERNAME: postgres
      TEST_PASSWORD: password
      TEST_DB_NAME: db_name
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
      TEST_DB_CONNECTION: pgsql
      TEST_TIMEZONE: Africa/Lagos
      TEST_SSLMODE: disable
      TEST_MIGRATE: true
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.TEST_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.TEST_PASSWORD }}
          POSTGRES_DB: ${{ env.TEST_DB_NAME }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Create app config file
        run: cp app-sample.env app.env
      - name: Build the application
        run: go build -o development_app
      - name: Run the application
        run: nohup ./development_app > /dev/null 2>&1 &
      - name: Wait for application to start
        run: sleep 30s
      - name: Test for reachability
        run: curl http://localhost:8019
      - name: Create log file
        run: mkdir logs && mkdir logs/app.log
      - name: Run All Tests
        run: go test ./... -timeout 99999s

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push'
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SERVER_PORT: 7000
      DB_NAME: "development_db"
      USERNAME: "development_user"
      APP_NAME: "development"
      APP_URL: "http://localhost:7000"

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ env.SSH_PORT }}
          script: |
            export APPROOT=~/deployments/development
            mkdir -p $APPROOT
            cd $APPROOT

            if [ -d "$APPROOT/.git" ]; then
              # Navigate to the repository directory and pull changes
              cd $APPROOT || { echo "Failed to navigate to web root directory"; exit 1; }
              git reset --hard HEAD || { echo "Failed to reset local changes"; exit 1; }
              git pull origin dev || { echo "Failed to pull latest changes"; exit 1; }
            else
              git clone -b dev https://github.com/${{ github.repository}} . || { echo "Failed to clone repository"; exit 1; }
            fi

            bash ./scripts/deploy_app.sh development https://github.com/${{ github.repository}} SERVER_PORT=${{ env.SERVER_PORT }} DB_NAME=${{ env.DB_NAME }} USERNAME=${{ env.USERNAME }} APP_NAME=${{ env.APP_NAME }} APP_URL=${{ env.APP_URL }} MIGRATE=true
